export const enum FileModelType {
  SERVICE_OUTLETS = 'SERVICE_OUTLETS',

  TRANSACTION_ACCOUNTS = 'TRANSACTION_ACCOUNTS',

  PREPAYMENT_ENTRIES = 'PREPAYMENT_ENTRIES',

  AMORTIZATION_ENTRIES = 'AMORTIZATION_ENTRIES',
}
